### ISSUE TITLE
ImportError: No module named ipython_genutils

### ISSUE THREAD

**Issue by cristianmtr** [ipython/ipython_genutils#3]
I'm running Python 2.7 on Windows 7 x64. I installed ipython and jupyter with pip. When doing "ipython notebook" I got the error "ImportError: No module named ipython_genutils". I was able to fix this by downloading this repo and installing it "python setup.py install". Is this normal?

**Comment by takluyver** [comment]
If you did `pip install jupyter`, that should have pulled in `ipython_genutils` as a dependency.

**Comment by cristianmtr** [comment]
I did that, and I was still getting the error

**Comment by nikolas** [comment]
I also did that and still got the error. I had to explicitly list `ipython_genutils==0.1.0` in `requirements.txt`.

**Comment by minrk** [comment]
@nikolas can you share the output of the install command?

**Comment by minrk** [comment]
And `pip list`?

**Comment by peter-d** [comment]
I had the same issue, python 2.7 on linux. Specifically adding `ipython_genutils` indeed fixed the problem. It seems it does not get installed when installing jupyter or ipython.

**Comment by minrk** [comment]
Can anyone provide a complete example that reproduces the problem (including pip, setuptools, Python and OS version)? `ipython_genutils` is listed as a strict dependency, and does get installed when you install these things with pip, so I'm wondering what it is that's allowing dependencies to be left out.

**Comment by beyonddoor** [comment]
after install ipython with no complains, `ipython --version`output:
Traceback (most recent call last):
  File "C:\Python27-64\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27-64\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27-64\Scripts\ipython.exe__main__.py", line 5, in <module>
  File "C:\Python27-64\lib\site-packages\IPython__init__.py", line 48, in <modu
le>
    from .core.application import Application
  File "C:\Python27-64\lib\site-packages\IPython\core\application.py", line 22,
in <module>
    from traitlets.config.application import Application, catch_config_error
  File "C:\Python27-64\lib\site-packages\traitlets__init__.py", line 1, in <mod
ule>
    from .traitlets import *
  File "C:\Python27-64\lib\site-packages\traitlets\traitlets.py", line 55, in <m
odule>
    from ipython_genutils import py3compat
ImportError: No module named ipython_genutils 

the output of `pip list`is:
backports.shutil-get-terminal-size (1.0.0)
cycler (0.10.0)
decorator (4.0.10)
ipython (4.2.0)
matplotlib (1.5.1)
numpy (1.11.0)
path.py (7.7.1)
pickleshare (0.7.2)
pip (1.5.6)
pyparsing (2.1.5)
python-dateutil (2.5.3)
pytz (2016.4)
setuptools (23.0.0)
simplegeneric (0.8.1)
six (1.10.0)
traitlets (4.2.1)
virtualenv (15.0.2)

`python --version`
Python 2.7.9

OS: win7 sp1

any helps?

**Comment by takluyver** [comment]
I'm still not sure how people get this. `pip install ipython_genutils` should fix it.

> pip (1.5.6)

That's quite old, it's recommended that you upgrade by running:

```
pip install --upgrade setuptools pip
```

**Comment by beyonddoor** [comment]
Following your instructions above, it complains "ImportError: No module named pathlib2", after `pip install pathlib2`, it now works, thanks. @takluyver

**Comment by videlec** [comment]
Some full tracebacks with detailed architecture/system available at https://trac.sagemath.org/ticket/24088

**Comment by yasirroni** [comment]
> ipython_genutils
> 
> the output of `pip list`is: backports.shutil-get-terminal-size (1.0.0) cycler (0.10.0)

I'm not really sure, but for those that is interested, in my case, the bug might be due to:

1. Create an environment that contains jupyter
2. Running a cell that contains !pip install that alter package in the environment.
3. Running notebooks via script in sequential make second notebook use packages altered by the first notebook.

It ended up this import error due tu incompatibilities.
